### ISSUE TITLE
Butterflies Not Appearing When Spawned

### ISSUE THREAD

**Issue by HamberAlert** [doc-bok/Butterflies#108] opened 2024-02-20 03:35 UTC
As said in the title, butterflies aren't showing up when spawned nor are the eggs, chrysalises and caterpillars. Currently playing on 1.20.1 with a personally made modpack. I've turned off my shaders and resource packs and they still aren't showing up.

**Comment by doc-bok** [comment] 2024-02-20 08:37
I can't reproduce this one locally :(

Can you confirm you're using the latest version of the mod (3.0.2)? Also are you running just a client, or are you connecting to a server? A list of mods might help as well - it could be a bad mod interaction.

**Comment by doc-bok** [comment] 2024-10-30 07:33
Closing this as cannot reproduce.

**Closed by doc-bok** 2024-10-30 07:33 UTC
Labels: bug, question
